version: "3.8"

services:
    swapi:
        build:
            dockerfile: ./Dockerfile
            context: .
        env_file: ./.env
        ports:
            - "8000:8000"
        volumes:
            - ./:/app/
    memcached:
        image: memcached:latest
        ports:
            - "11211:11211"